name: egui Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - main
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  run_tests:
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/general.yml
  check_wasm:
    needs: run_tests
    uses: ./.github/workflows/wasm.yml
  build-github-pages:
    needs: check_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
      - name: Change to client folder
        run: cd crates/client
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: ./trunk build --release --public-url $public_url
        env:
          public_url: "https://dev.chester.wykies.com/${{ github.event.repository.name }}"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
