name: Rust WASM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  pull_request: 
    branches:
      - develop
  workflow_call:
      
env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy WASM
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
          components: clippy
      - name: Linting
        run: cd crates/client && cargo clippy --target="wasm32-unknown-unknown" -- -D warnings
    
  trunk:
    name: trunk
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
      - name: Install Trunk
        uses: taiki-e/install-action@main
        with:
          tool: trunk
      - name: Build
        run: cd crates/client && trunk build